scanPackage: com.zookao.admin.controller
server:
    error:
        include-binding-errors: always
        include-exception: true
        include-message: always
        include-stacktrace: always
    servlet:
        context-path: /admin
spring:
    profiles:
        active: dev
    servlet:
        multipart:
            max-file-size: 2000MB
